name: Checking the version and testing the Python file.

on: push
jobs:
  version-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing the Python version...
        run: python --version
  testing-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing Pylint...
        run: pip install pylint
      - name: Installing Flask...
        run: pip install flask
      - name: Running Pylint...
        run: pylint app.py
 
